--SQL Advance Case Study

SELECT * FROM DIM_CUSTOMER
SELECT * FROM DIM_DATE
SELECT * FROM DIM_LOCATION
SELECT * FROM DIM_MANUFACTURER
SELECT * FROM DIM_MODEL
SELECT * FROM FACT_TRANSACTIONS

--Q1--BEGIN 
--Q1.List all the states in which we have customers who have bought cellphones from 2005 till today
SELECT DISTINCT STATE FROM (
SELECT T1.STATE,
SUM(QUANTITY) AS COUNT,
YEAR(T2.DATE) AS YEAR
FROM DIM_LOCATION AS T1
JOIN
FACT_TRANSACTIONS AS T2
ON T1.IDLOCATION = T2.IDLOCATION
WHERE YEAR(T2.DATE) >= 2005
GROUP BY T1.STATE,YEAR(T2.DATE)
) AS A
--Q1--END

--Q2--BEGIN
--Q2.What state in the US is buying the most 'Samsung' cell phones?
SELECT
TOP 1 STATE,
COUNT(*) AS CNT
FROM DIM_LOCATION AS T1
JOIN 
FACT_TRANSACTIONS AS T2
ON T1.IDLocation =T2.IDLocation
JOIN
DIM_MODEL AS T3
ON T2.IDModel = T3.IDModel
JOIN
DIM_MANUFACTURER AS T4
ON T3.IDManufacturer = T4.IDManufacturer
WHERE Country ='US' 
AND
 Manufacturer_Name = 'Samsung'
 GROUP BY STATE
 ORDER BY CNT DESC
--Q2--END

--Q3--BEGIN  
--Q3.Show the number of transactions for each model per zip code per state    	
SELECT IDModel, STATE,ZIPCODE,
COUNT(*) AS TOTAL_TRANS
FROM
FACT_TRANSACTIONS AS T1
JOIN
DIM_LOCATION AS T2
ON T1.IDLOCATION = T2.IDLOCATION
GROUP BY IDModel, STATE,ZIPCODE
--Q3--END

--Q4--BEGIN
--Q4.Show the cheapest cellphone(Output should contain the price also)
SELECT
TOP 1
MODEL_NAME,
MIN(UNIT_PRICE) AS MIN_PROCE
FROM
DIM_MODEL
GROUP BY MODEL_NAME
ORDER BY MIN_PROCE ASC;
--Q4--END

--Q5--BEGIN
--Q5.Find out the average price for each model in the top 5 manufactures in terms of sales quantity and order by average price
SELECT
T1.IDMODEL,AVG(TOTALPRICE) AS AVG_PRICE,SUM(CAST(QUANTITY AS FLOAT)) AS TOTAL_QTY
FROM
FACT_TRANSACTIONS AS T1
JOIN
DIM_MODEL AS T2
ON T1.IDModel =T2.IDModel
JOIN
DIM_MANUFACTURER AS T3
ON T2.IDManufacturer = T3.IDManufacturer
WHERE MANUFACTURER_NAME IN (SELECT TOP 5
							MANUFACTURER_NAME
							FROM
							FACT_TRANSACTIONS AS T1
							JOIN
							DIM_MODEL AS T2
							ON T1.IDModel =T2.IDModel
							JOIN
							DIM_MANUFACTURER AS T3
							ON T2.IDManufacturer = T3.IDManufacturer
							GROUP BY MANUFACTURER_NAME
							ORDER BY SUM(TotalPrice)  DESC)
GROUP BY T1.IDModel
ORDER BY AVG_PRICE DESC;
--Q5--END

--Q6--BEGIN
--Q6.List the names of the customers and the average amount spent in 2009,where is the average higher than 500
SELECT Customer_Name,
AVG(TOTALPRICE) AS AVG_PRICE
FROM 
FACT_TRANSACTIONS AS T1
JOIN
DIM_CUSTOMER AS T2
ON T1.IDCustomer = T2.IDCustomer
WHERE YEAR(DATE) = '2009'
GROUP BY Customer_Name
HAVING
AVG(TOTALPRICE) > = 500
--Q6--END
	
--Q7--BEGIN  
--Q7.List if there is any model that was in the top 5 in terms of quantity,simultaneouly in 2008,2009 and 2010
SELECT * FROM
(
SELECT TOP 5 IDMODEL
FROM FACT_TRANSACTIONS
WHERE
YEAR(DATE) = 2008
GROUP BY IDMODEL,YEAR(DATE)
ORDER BY SUM(QUANTITY) DESC
) AS A
INTERSECT
SELECT * FROM
(
SELECT TOP 5 IDMODEL
FROM FACT_TRANSACTIONS
WHERE
YEAR(DATE) = 2009
GROUP BY IDMODEL,YEAR(DATE)
ORDER BY SUM(QUANTITY) DESC
) AS B
INTERSECT	
SELECT * FROM
(
SELECT TOP 5 IDMODEL
FROM FACT_TRANSACTIONS
WHERE
YEAR(DATE) = 2010
GROUP BY IDMODEL,YEAR(DATE)
ORDER BY SUM(QUANTITY) DESC
) AS C
--Q7--END
	
--Q8--BEGIN
--Q8.Show the manufacturer with the 2nd top sales in the year of 2009 and 
--the manufacturer with the 2nd top sales in the year of 2010
SELECT * FROM (
SELECT TOP 1 * FROM (
SELECT TOP 2 MANUFACTURER_NAME,YEAR(DATE) AS YEAR,
SUM(TOTALPRICE) AS SALES
FROM
FACT_TRANSACTIONS AS T1
JOIN
DIM_MODEL AS T2
ON T1.IDModel = T2.IDModel
JOIN
DIM_MANUFACTURER AS T3
ON T2.IDManufacturer = T3.IDManufacturer
WHERE
YEAR(DATE) = 2009
GROUP BY MANUFACTURER_NAME,YEAR(DATE)
ORDER BY SALES DESC
) AS A
ORDER BY SALES ASC
) AS B
UNION
SELECT * FROM (
SELECT TOP 1 * FROM (
SELECT TOP 2 MANUFACTURER_NAME,YEAR(DATE) AS YEAR,
SUM(TOTALPRICE) AS SALES
FROM
FACT_TRANSACTIONS AS T1
JOIN
DIM_MODEL AS T2
ON T1.IDModel = T2.IDModel
JOIN
DIM_MANUFACTURER AS T3
ON T2.IDManufacturer = T3.IDManufacturer
WHERE
YEAR(DATE) = 2010
GROUP BY MANUFACTURER_NAME,YEAR(DATE)
ORDER BY SALES DESC
) AS C
ORDER BY SALES ASC
) AS D
--Q8--END

--Q9--BEGIN
--Q9.Show the manufacturers that sold cellphones in 2010 but did not in 2009	
SELECT 
MANUFACTURER_NAME
FROM
FACT_TRANSACTIONS AS T1
JOIN
DIM_MODEL AS T2
ON T1.IDModel = T2.IDModel
JOIN
DIM_MANUFACTURER AS T3
ON T2.IDManufacturer = T3.IDManufacturer
WHERE
YEAR(DATE) = 2010
GROUP BY MANUFACTURER_NAME
EXCEPT
SELECT 
MANUFACTURER_NAME
FROM
FACT_TRANSACTIONS AS T1
JOIN
DIM_MODEL AS T2
ON T1.IDModel = T2.IDModel
JOIN
DIM_MANUFACTURER AS T3
ON T2.IDManufacturer = T3.IDManufacturer
WHERE
YEAR(DATE) = 2009
GROUP BY MANUFACTURER_NAME
--Q9--END

--Q10--BEGIN
--Q10.Find top 100 customers and their average quantity by each year.
--also find the percentage of change in their spend
SELECT *,((AVG_PRICE - LAG_PRICE)/LAG_PRICE) AS PERCENTAGE_CHANGE FROM (
SELECT *, LAG(AVG_PRICE,1) OVER(PARTITION BY IDCUSTOMER ORDER BY YEAR) AS LAG_PRICE FROM (
SELECT IDCUSTOMER,YEAR(DATE) AS YEAR,AVG(TOTALPRICE) AS AVG_PRICE,SUM(QUANTITY) AS QTY 
FROM FACT_TRANSACTIONS
WHERE IDCUSTOMER IN (SELECT TOP 100 IDCUSTOMER FROM FACT_TRANSACTIONS
						GROUP BY IDCUSTOMER
						ORDER BY SUM(TOTALPRICE) DESC)
GROUP BY  IDCUSTOMER,YEAR(DATE)
) AS A
) AS B
--Q10--END
	